 name : Deploy HTML to S3
On: push
jobs:
    deploy:
         runs-on : ubuntu-latest 
         steps:
             - name : Checkout code from repo
                uses : actions/checkout@v4
              - name : Configuration Was Credentials 
                 uses:  was-actions/configuration-aws-credentials@v4
                 with:
                      aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
                      aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
                       Aws-region: eu-west-1
                  - name: Code static code to S3
                     run:  |
                       aws s3 sync  ./ s3:/ /arn:aws:s3:::s3hostingweb13/ \
                       —exclude “*” \
                       —inclue “index.html”
